[package]
name = "bevy_rng"
version = "0.1.0"
authors = ["Jean Mertz <git@jeanmertz.com>"]
edition = "2018"

[dependencies]
bevy = { version = "0.4", default-features = false }
rand = { version = "0.8", default-features = false }
rand_seeder = "0.2"
rand_xorshift = "0.3"
